# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0c854433ba8bda598bec750070e6236f3379a92362fa1d9f7ca29f15f132a07f49fda2b946edec5712de84ff29d2f4e8549a2adf839f6f5c64bfc44c4ce3a0

test:
  secret_key_base: 8c0f69f5e773f9b421aaf7f2a2bcbd8d0209b713795f831e8a58905dfe82b4e795c14960655a2c082d08d4c971a9fbff1b6585293a4bed53f4b5f1075b212511

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
